# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define :clienteUbuntu do |clienteUbuntu|
    clienteUbuntu.vm.box = "bento/ubuntu-22.04"
    clienteUbuntu.vm.network :private_network, ip: "192.168.100.2"
    clienteUbuntu.vm.hostname = "clienteUbuntu"
    # Configuración de Directorio Sincronizado para el cliente
    clienteUbuntu.vm.synced_folder "C:\\Users\\SkeltonPC\\Documents\\CURSOS 2024 ESP IA\\Vagrant's Files\\Actividad 1\\directorioSincronizadoWindows", "/home/vagrant/directorioSincronizado"
  end

  config.vm.define :servidorUbuntu do |servidorUbuntu|
    servidorUbuntu.vm.box = "bento/ubuntu-22.04"
    servidorUbuntu.vm.network :private_network, ip: "192.168.100.3"
    servidorUbuntu.vm.hostname = "servidorUbuntu"
    # Configuración de Directorio Sincronizado para el servidor
    servidorUbuntu.vm.synced_folder "C:\\Users\\SkeltonPC\\Documents\\CURSOS 2024 ESP IA\\Vagrant's Files\\Actividad 1\\directorioSincronizadoWindows", "/home/vagrant/directorioSincronizado"
  end
end